#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: 1.0.0

# server 所用到配置部分设置
server:
  restful:
    certcommonname: brilliance1.com
    clientport: :8888